//API key: d728a6e44887606acf25b66f03b1fe4df3a59437

var data = {
status: "OK",
usage: "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
totalTransactions: "60",
result: {
docs: [
{
id: "Mjg4NzU5OTAzNnwxNDQxNTYzMzI2",
source: {
enriched: {
url: {
text: "Large customers of Xcel Energy Inc. that signed up for shared solar energy projects are getting squeezed by a new size restriction and may not get all the solar power or cost savings they expected. This problem affects Ecolab Inc. and Macalester College in St. ...",
title: "Big power users face potentially smaller harvest from solar gardens - StarTribune.com",
url: "http://www.startribune.com/big-power-users-face-potentially-smaller-harvest-from-community-solar-gardens-in-minnesota/324589111/"
}
}
},
timestamp: 1441563326
},
{
id: "Mjg4NTcxOTc1MnwxNDQxNTYyOTg5",
source: {
enriched: {
url: {
text: "Large customers of Xcel Energy Inc. that signed up for shared solar energy projects are getting squeezed by a new size restriction and may not get all the solar power or cost savings they expected. This problem affects Ecolab Inc. and Macalester College in St. ...",
title: "Big power users face potentially smaller harvest from solar gardens - StarTribune.com",
url: "http://www.startribune.com/big-power-users-face-potentially-smaller-harvest-from-community-solar-gardens-in-minnesota/324589111/"
}
}
},
timestamp: 1441562989
},
{
id: "Mjg4MTY4MjQ5MnwxNDQxNTYxODIy",
source: {
enriched: {
url: {
text: "PALIN: 'I think a lot about the Department of Energy, because energy is my baby: oil and gas and minerals, those things that God has dumped on this part of the Earth for mankind's use instead of us relying on unfriendly foreign nations...' Ironically, she is the only potential cabinet nominee to happily speak of dissolving her own position once she attains it. 'I'd get rid of it. ...'",
title: "Palin Wants To Lead Trump's D.O.E. So She Could Get Rid Of It | Crooks and Liars",
url: "http://crooksandliars.com/2015/09/palin-wants-lead-trumps-doe-so-she-can-get"
}
}
},
timestamp: 1441561822
},
{
id: "Mjg4MTEwNDM3NnwxNDQxNTYxNzk3",
source: {
enriched: {
url: {
text: "An issue of Peabody Energy (NYSE:BTU) bonds fell 8.5% against their face value during trading on Friday, Market Beat Ratings reports. The debt issue has a 6% coupon and will mature on November 15, 2018. ...",
title: "Peabody Energy Bonds Drop 8.5% During Trading (BTU)",
url: "http://www.dakotafinancialnews.com/peabody-energy-bonds-drop-8-5-during-trading-btu/411810/"
}
}
},
timestamp: 1441561797
},
{
id: "Mjg3MDMyNjc0NnwxNDQxNTYxNjM2",
source: {
enriched: {
url: {
text: "I have always approached decision-making with both my head and my heart, and depending on the nature of the choice, sometimes lean more on one versus the other. My review of the Joint Comprehensive Plan of Action, a monumental agreement negotiated by the United States, the other P5+1 nations and Iran to quell Iran’s nuclear-weapons ambitions, has been no exception. ...",
title: "Wasserman Schultz explains decision in lengthy Miami Herald op-ed | The Charlotte Observer",
url: "http://www.charlotteobserver.com/news/nation-world/national/article34239480.html"
}
}
},
timestamp: 1441561636
},
{
id: "Mjg4MDkwNjI2MHwxNDQxNTYxNjEx",
source: {
enriched: {
url: {
text: "WINCHESTER, Ky. (AP) — George Campbell has spent 33 years in the military community. Eight of those years were served in uniform and the rest have been in a civilian capacity. ...",
title: "Veterans to be flown from Kentucky to Washington memorials | State News | bgdailynews.com",
url: "http://www.bgdailynews.com/news/state/veterans-to-be-flown-from-kentucky-to-washington-memorials/article_993b1bb2-0240-594b-b538-826b24cce49a.html"
}
}
},
timestamp: 1441561611
},
{
id: "Mjg3MDA2MzcwNXwxNDQxNTYxNTk5",
source: {
enriched: {
url: {
text: "MANILA, Philippines – The 21 member economies of the Asia-Pacific Economic Cooperation (APEC) are being urged to join the Regional Sharing Initiative to determine appropriate projects that will help in achieving energy efficiency goals in the next 20 years. In a statement disseminated by the Department of Energy, the APEC Expert Group in Energy Efficiency & Conservation (EGEEC), in its 46th meeting held last week in Cebu City, has reaffirmed its commitment to intensify efforts to reduce the aggregate energy intensity by 45 percent based on the 2005 level by 2035. ...",
title: "APEC urged to enhance knowledge sharing to hit energy efficiency goals | Business, News, The Philippine Star | philstar.com",
url: "http://www.philstar.com/business/2015/09/07/1496716/apec-urged-enhance-knowledge-sharing-hit-energy-efficiency-goals"
}
}
},
timestamp: 1441561599
},
{
id: "Mjg3MzQxNTE0MHwxNDQxNTYxNDU3",
source: {
enriched: {
url: {
text: "In the near future, when you need to charge your smartphone, you could just let it soak up a few solar rays. That's because your screen could be a solar-powered transparent battery. ...",
title: "These solar-charging transparent batteries could change smartphones forever | Komando.com",
url: "http://www.komando.com/happening-now/324197/these-solar-charging-transparent-batteries-could-change-smartphones-forever"
}
}
},
timestamp: 1441561457
},
{
id: "Mjg3OTg5MjUwM3wxNDQxNTYxMzM1",
source: {
enriched: {
url: {
text: "Did I get your attention with that title? I promise, it's not hyperbole. ...",
title: "How to Dramatically Improve Your TV's Performance in 10 Seconds",
url: "http://hometheaterreview.com/how-to-dramatically-improve-your-tvs-performance-in-10-seconds/"
}
}
},
timestamp: 1441561335
},
{
id: "Mjg3OTA2NDUyNHwxNDQxNTYxMzA0",
source: {
enriched: {
url: {
text: "HOUSTON, Sept. 3, 2015 /PRNewswire/ -- PATTERSON-UTI ENERGY, INC. (PTEN) today reported that for the month of August 2015, the Company had an average of 106 drilling rigs operating in the United States and four rigs in Canada.  For the two months ended August 31, 2015, the Company had an average of 109 drilling rigs operating in the United States and four rigs in Canada. Average drilling rigs operating reported in the Company's monthly announcements represent the average number of the Company's drilling rigs that were operating under a drilling contract.  The Company cautioned that numerous factors in addition to average drilling rigs operating can impact the Company's operating results and that a particular trend in the number of drilling rigs operating may or may not indicate a trend in or be indicative of the Company's financial performance.  The Company intends to continue providing monthly updates on drilling rigs operating shortly after the end of each month. ...",
title: "Patterson-UTI Reports Drilling Activity for August 2015 - Yahoo Finance",
url: "http://finance.yahoo.com/news/patterson-uti-reports-drilling-activity-100000756.html"
}
}
},
timestamp: 1441561304
},
{
id: "Mjg2NTYzMDM3OHwxNDQxNTYwNTAy",
source: {
enriched: {
url: {
text: " The Renewable Energy Markets Association (REMA) applauds the Environmental Protection Agency (EPA) for releasing a strong, achievable final Clean Power Plan. We look forward to working with the states to ensure that purchases of renewable energy and their environmental credits are used to comply with the plan, state goals and to reach beyond them by encouraging voluntary purchases. ...",
title: "North American Clean Energy - Renewable Energy Markets Association Response to EPA's Final Clean Power Plan",
url: "http://www.nacleanenergy.com/articles/21070/renewable-energy-markets-association-response-to-epa-s-final-clean-power-plan"
}
}
},
timestamp: 1441560502
},
{
id: "Mjg2NDk3NTUyOHwxNDQxNTYwNDQy",
source: {
enriched: {
url: {
text: "Kentucky coal miners bled and died to unionize. Their workplaces became war zones, and gun battles once punctuated union protests. ...",
title: "No union mines left in Kentucky, where labor wars once raged | www.kirotv.com",
url: "http://www.kirotv.com/news/ap/top-news/no-union-mines-left-in-kentucky-where-labor-wars-o/nnYrd/"
}
}
},
timestamp: 1441560442
}
],
next: "MTAyNzE4OTE0MzAzNDE2MzQxNjd8TWpnM09UZzVNalV3TTN3eE5EUXhOVFl4TXpNMXwxMDkyNTgxMTgwNjA3MzE5MzQwMXxNamczT1RBMk5EVXlOSHd4TkRReE5UWXhNekEwfDE0NjE2MDMxNDUyNzYyMzAxOTY0fE1qZzJORGszTlRVeU9Id3hORFF4TlRZd05EUXl8MTczMDU4NjAxNDg3NzI0OTQ5MjF8TWpnM016UXhOVEUwTUh3eE5EUXhOVFl4TkRVMw",
status: "OK"
}
}

$(document).ready( function() {

	var articleData = data.result.docs;

	for (i=0; i<articleData.length; i++) {
		displayArticle(articleData[i]);
	}

});

function displayArticle(articleData) {
	
	var article = $('.article:last');
	//set Title and link
	var title = article.find('a');
	title.attr('href', articleData.source.enriched.url.url);
	//console.log(articleData.source.enriched.url.url);
	title.text(articleData.source.enriched.url.title);
	//console.log(articleData.source.enriched.url.title);

	//add text snippet
	var snippet = article.find('p');
	snippet.text(articleData.source.enriched.url.text);

	//add related keyword tags

	//add keyword links to spawn new search

	newArticle = $('#article-list').append('<div class="col-md-2 col-sm-3 article"><h3><a href="" target="_blank"></a></h3><p></p></div>');
	return newArticle;

}

